spring:
  application:
    name: User-Service
  config:
    import: configserver:http://localhost:8085
#  profiles:
#    active: prod

  datasource:
    url: jdbc:mysql://avnadmin:AVNS_bQBsh-dHmCoQVd6N44F@microservices-rishi-microservices1.e.aivencloud.com:24124/microservices?ssl-mode=REQUIRED
    # url: jdbc:mysql://localhost:3307/microservices
    username: avnadmin
    password: AVNS_bQBsh-dHmCoQVd6N44F
    # driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
server:
  port: 8081

management:
  health:
    circuitbreakers:
      enabled: true;
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  rateLimiter:
    instance:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeOutDuration: 0s


